[package]
name = "z2p"
version = "0.1.0"
authors = ["Darshan Kumawat <kumawatdarshan.1304@gmail.com>"]
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "z2p"

[dependencies]
axum = {version = "0.8.4", features = ["macros"]}
config = "0.15.13"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.46.0", features = ["full"] }
tower = { version = "0.5.2", features = ["full"] }
uuid = { version = "1.17.0", features = ["v4"] }
chrono = { version = "0.4.41", default-features = false, features = ["clock"] }

[dependencies.sqlx]
version = "0.8.6"
default-features = false
features = [
"runtime-tokio-rustls",
"macros",
"postgres",
"uuid",
"chrono",
"migrate"
]

[dev-dependencies]
reqwest = "0.12.22"
