[package]
name = "z2p"
version = "0.1.0"
authors = ["Darshan Kumawat <kumawatdarshan.1304@gmail.com>"]
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "z2p"

[dependencies]
axum = "0.8.4"
serde = { version = "1.0.219", features = ["derive"] }
# hyper = { version = "1.6.0", features = ["full"] }
tokio = { version = "1.46.0", features = ["full"] }

[dev-dependencies]
reqwest = "0.12.22"
