name: Check and perform Tests
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Set up Rust cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # TODO: uncomment after fixing postgres
      # - name: Check Rust formatting
      #   run: |
      #     nix develop --command \
      #       cargo fmt --check

      # - name: Lint Code
      #   run: nix develop --command cargo clippy -- -D warnings

      - name: Parse config and export env vars
        run: |
          nix develop --command config-to-env >> $GITHUB_ENV

      - name: Start Postgres Instance
        run: |
          rm -rf ./data
          nix develop --command process-compose -t=false

      - name: Run tests
        run: nix develop --command cargo test

