name: Rust
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Set up Rust cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check Rust formatting
        run: |
          nix develop --command \
            cargo fmt --check

      - name: Lint Code
        run: nix develop --command cargo clippy -- -D warnings

      - name: Parse config and export env vars
        run: |
          nix develop --command config-to-env >> $GITHUB_ENV

      - name: Start Postgres Instance
        run: |
          nix develop --command process-compose -D

      - name: Migrate Database
        run: |
          export DATABASE_URL=postgres://${DB_USER}:${DB_USER_PWD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
          nix develop --command sqlx database create
          nix develop --command sqlx migrate run

      - name: Run tests
        run: nix develop --command cargo test

